[mypy]
mypy_path = .
explicit_package_bases = False

python_version = 3.12
warn_unused_ignores = True
no_implicit_optional = True
strict_optional = True

exclude = ^chap14_8[\\/].*|^\.venv|^build[\\/]|^dist[\\/]|^\.mypy_cache

show_error_context = False
error_summary = False

[mypy-chap14_8.*]
ignore_errors = True
follow_imports = silent

[mypy-utils.tasks]
disable_error_code = annotation-unchecked

check_untyped_defs = True

[mypy-agent.web_search]
check_untyped_defs = True

[mypy-tools.web_rag.ingest]
check_untyped_defs = True

[mypy-graph]
check_untyped_defs = True